name: build_android

on: 
  push:
    paths: 
      - XdeltaLib/**
      - .github/workflows/build_android.yml

jobs:
   build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: echo "Setting up JDK" 
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - run: echo "The workflow is now ready to test your code."
    - name: Grant execute permission for gradlew
      run: chmod +x ./XdeltaLib/gradlew
    - run: echo "Building Debug AAR."  
    - name: Build with Gradle
      run: |
        cd XdeltaLib
        ./gradlew build
    - run: echo "Build status report=${{ job.status }}."

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./XdeltaLib/app/build/outputs/aar/app-release.aar
        name: xdelta3_lib
