name: build

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/main.yml

jobs:
   windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
         msbuild-architecture: x64
    - name: Build app for debug
      run: msbuild xdelta3\xdelta3.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Debug
     

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./xdelta3/x64/**/*
        name: xdelta3_x64
